export interface IndustryPartnerCredential {
  name: string;
  email: string;
  password: "Password@123";
  domain: string;
  location: string;
  initials: string;
  badgeTone: "indigo" | "blue" | "emerald" | "amber" | "violet" | "red" | "pink" | "cyan";
}

export const ALL_INDUSTRY_PARTNERS: IndustryPartnerCredential[] = [
  {
    name: "Google India",
    email: "university-india@google.com",
    password: "Password@123",
    domain: "Google Cloud & Applied AI Labs",
    location: "Bengaluru, Karnataka",
    initials: "GO",
    badgeTone: "indigo",
  },
  {
    name: "Microsoft India",
    email: "india-recruitment@microsoft.com",
    password: "Password@123",
    domain: "Azure Systems & Applied Research",
    location: "Hyderabad, Telangana",
    initials: "MS",
    badgeTone: "blue",
  },
  {
    name: "Amazon AWS",
    email: "aws-university@amazon.com",
    password: "Password@123",
    domain: "AWS Cloud Systems Architecture",
    location: "Bengaluru, Karnataka",
    initials: "AW",
    badgeTone: "amber",
  },
  {
    name: "NVIDIA India",
    email: "developer-edu@nvidia.com",
    password: "Password@123",
    domain: "Deep Learning & Accelerated Computing",
    location: "Pune, Maharashtra",
    initials: "NV",
    badgeTone: "emerald",
  },
  {
    name: "Intel India",
    email: "labs-fellowship@intel.com",
    password: "Password@123",
    domain: "Intel Labs & Silicon Design",
    location: "Bengaluru, Karnataka",
    initials: "IN",
    badgeTone: "cyan",
  },
  {
    name: "Cisco Systems",
    email: "networking-academy@cisco.com",
    password: "Password@123",
    domain: "Enterprise Networking & Zero-Trust",
    location: "Bengaluru, Karnataka",
    initials: "CS",
    badgeTone: "emerald",
  },
  {
    name: "IBM India Research",
    email: "research-collaborations@ibm.com",
    password: "Password@123",
    domain: "Hybrid Cloud & Quantum Systems",
    location: "Bengaluru, Karnataka",
    initials: "IB",
    badgeTone: "indigo",
  },
  {
    name: "Qualcomm India",
    email: "campus-relations@qualcomm.com",
    password: "Password@123",
    domain: "Wireless Systems & Snapdragon Edge AI",
    location: "Hyderabad, Telangana",
    initials: "QC",
    badgeTone: "red",
  },
  {
    name: "Adobe Systems",
    email: "adobe-labs@adobe.com",
    password: "Password@123",
    domain: "Digital Media & Experience Platform",
    location: "Noida, Uttar Pradesh",
    initials: "AD",
    badgeTone: "pink",
  },
  {
    name: "Infosys",
    email: "recruit@infosys.com",
    password: "Password@123",
    domain: "Talent Acquisition & Innovation Labs",
    location: "Bengaluru, Karnataka",
    initials: "IF",
    badgeTone: "blue",
  },
  {
    name: "TCS",
    email: "campus@tcs.com",
    password: "Password@123",
    domain: "Cognitive Business Operations",
    location: "Pune, Maharashtra",
    initials: "TC",
    badgeTone: "blue",
  },
  {
    name: "Wipro",
    email: "talent@wipro.com",
    password: "Password@123",
    domain: "Digital Operations & Cyber Resilience",
    location: "Bengaluru, Karnataka",
    initials: "WP",
    badgeTone: "emerald",
  },
  {
    name: "Zoho",
    email: "campus@zohocorp.com",
    password: "Password@123",
    domain: "Platform Engineering & SaaS",
    location: "Chennai, Tamil Nadu",
    initials: "ZH",
    badgeTone: "amber",
  },
  {
    name: "HCLTech",
    email: "careers@hcltech.com",
    password: "Password@123",
    domain: "Engineering and R&D Services",
    location: "Noida, Uttar Pradesh",
    initials: "HC",
    badgeTone: "violet",
  },
  {
    name: "L&T Technology Services",
    email: "careers@ltts.com",
    password: "Password@123",
    domain: "Smart Manufacturing & Industry 4.0",
    location: "Vadodara, Gujarat",
    initials: "LT",
    badgeTone: "amber",
  },
  {
    name: "Samsung R&D Institute",
    email: "sri.collaborate@samsung.com",
    password: "Password@123",
    domain: "Advanced Technology & Mobile Solutions",
    location: "Bengaluru, Karnataka",
    initials: "SS",
    badgeTone: "indigo",
  },
  {
    name: "Tata Motors",
    email: "ev-innovation@tatamotors.com",
    password: "Password@123",
    domain: "Electric Mobility & Connected Vehicles",
    location: "Pune, Maharashtra",
    initials: "TM",
    badgeTone: "blue",
  },
  {
    name: "Reliance Jio Platforms",
    email: "jio-innovations@ril.com",
    password: "Password@123",
    domain: "5G Telecom & Indigenous AI Platforms",
    location: "Navi Mumbai, Maharashtra",
    initials: "RJ",
    badgeTone: "indigo",
  },
  {
    name: "All India Institute of Ayurveda (AIIA)",
    email: "research@aiia.gov.in",
    password: "Password@123",
    domain: "Ayush Bio-Informatics & Quality Screening",
    location: "New Delhi",
    initials: "AI",
    badgeTone: "emerald",
  },
];
